
CREATE TABLE EXPERIMENT (
    EXP_ID         INTEGER PRIMARY KEY,
    EXP_TARGET     TEXT
);
/


CREATE TABLE TEST (
    TEST_ID         INTEGER PRIMARY KEY,
    TEST_NUMBER     INTEGER,
    EXP_ID          INTEGER NOT NULL,
    TEST_MODE       TEXT DEFAULT 'classic',
    TEST_IT         INTEGER DEFAULT 0,
    TEST_HAS_ERRORS INTEGER DEFAULT 0,
    FOREIGN KEY(EXP_ID) REFERENCES EXPERIMENT(EXP_ID)
);
/


CREATE TABLE TEST_ITERATION (
    IT_ID           INTEGER PRIMARY KEY,
    TEST_ID         INTEGER NOT NULL,
    IT_EVENT        TEXT,
    IT_NUMBER       INTEGER NOT NULL,
    IT_DATE         DATE,
    IT_MODE         TEXT,
    FOREIGN KEY(TEST_ID) REFERENCES TEST(TEST_ID)
);
/


CREATE TABLE MESSAGE (
    MESSAGE_ID              INTEGER PRIMARY KEY,
    TEST_ID                 INTEGER NOT NULL,
    IT_ID                   INTEGER,
    MESSAGE_SRC             TEXT,
    MESSAGE_DST             TEXT,
    MESSAGE_KEY             TEXT,
    MESSAGE_PAYLOAD         TEXT,
    MESSAGE_ACTION          TEXT,
    MESSAGE_DATE            DATE,
    MESSAGE_PARAMS_COUNT    INTEGER,
    FOREIGN KEY(TEST_ID) REFERENCES TEST(TEST_ID),
    FOREIGN KEY(IT_ID) REFERENCES TEST_ITERATION(IT_ID)
);