
CREATE TABLE INJECTION (
    INJECTION_ID            INTEGER PRIMARY KEY,
    MESSAGE_ID              INTEGER NOT NULL,
    INJECTION_PARAM         TEXT,
    INJECTION_VALUE         TEXT,
    INJECTION_MUTATION      TEXT,
    INJECTION_OPERATOR      TEXT,
    INJECTION_PARAM_TYPE    TEXT,
    FOREIGN KEY(MESSAGE_ID) REFERENCES MESSAGE(MESSAGE_ID)
);
/