CREATE TABLE CONTROL (
    CONTROL_ID          INTEGER PRIMARY KEY,
    TEST_ID             INTEGER NOT NULL,
    CONTROL_STATE       TEXT,
    CONTROL_DATE        DATE,
    FOREIGN KEY (TEST_ID) REFERENCES TEST(TEST_ID)
);
/

CREATE TABLE TEST_LOG (
    LOG_ID              INTEGER PRIMARY KEY AUTOINCREMENT,
    LOG_SOURCE          TEXT,
    LOG_CONTENT         TEXT,
    TEST_ID             INTEGER NOT NULL,
    LOG_DATE            DATE,
    FOREIGN KEY (TEST_ID) REFERENCES TEST(TEST_ID)
);
/